name: "Bump version and publish to NPM"

on:
  push:
    branches:
      - "main"

jobs:
  bump-version-and-publish:
    name: "Bump version and publish to NPM"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            daisyui-svelte:
              - 'packages/daisyui-svelte/**'

      - name: "Bump daisyui-svelte package version"
        if: steps.filter.outputs.daisyui-svelte == 'true'
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-tag: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "packages/daisyui-svelte"

      - name: "Create package"
        if: steps.version-bump.outcome == 'success'
        id: create-package
        run: |
          npm install
          npm run package

      - name: "Publish daisyui-svelte package to NPM"
        if: steps.version-bump.outcome == 'success'
        uses: JS-DevTools/npm-publish@v2
        with:
          package: packages/daisyui-svelte
          access: public
          token: ${{ secrets.NPM_TOKEN }}
